Neel_Stock/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('verification/', include('verify_email.urls')),
    path('', include('accounts.urls')),
    path('core/', include('core.urls')),
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='accounts/password/password_reset_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name="accounts/password/password_reset_confirm.html"),
         name='password_reset_confirm'),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password/password_reset_complete.html'),
         name='password_reset_complete'),

]

accounts/urls.py
from django.urls import path
from .views import signin, signup, signout, change_password, password_reset_request, email_message

app_name = "accounts"   # App name for calling Url's in template/Html

urlpatterns = [
    path('', signin, name="login"),
    path('signout', signout, name="signout"),
    path('signup', signup, name="signup"),
    path('change-password', change_password, name="change-password"),
    path('password_reset/', password_reset_request, name="password_reset"),
    path('email-activation/', email_message, name="email-activation"),
]

core/urls.py
from django.urls import path
from .views import user_lists, watch_lists, delete_userlist, delete_watchlist, update_userlist,get_ajax, home, user_buckets, update_bucket, delete_bucket

app_name = 'core'

urlpatterns = [
    # dashboard
    path('', home, name='home'),
    # create and list views
    path('user_lists/', user_lists, name='user_lists'),
    path('user_buckets/', user_buckets, name='user_buckets'),
    path('watch_list/', watch_lists, name='watch_list'),
    # edit views
    path('update_user/<int:pk>/', update_userlist.as_view(), name='update_user'),
    path('update_bucket/<int:pk>/', update_bucket.as_view(), name='update_bucket'),

    # delete views
    path('delete_userlist/<int:pk>/', delete_userlist, name='delete_userlist'),
    path('delete_bucket/<int:pk>/', delete_bucket, name='delete_bucket'),
    path('delete_watchlist/<int:pk>/', delete_watchlist, name='delete_watchlist'),

    # ltp view
    path('ltp/', get_ajax, name='get_ltp'),
]

accounts/models.py
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField
from django.contrib.auth.models import User

from core.choices import BROKER_CHOICES


# Create your models here.

class Profile(models.Model):
    User = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')

    Broker = models.CharField(max_length=15, choices=BROKER_CHOICES, null=True, blank=True)  #
    UserId = models.CharField(max_length=128, null=True, blank=True)  #

    Password = models.CharField(max_length=256, null=True, blank=True)  #

    Pin_2FA = models.CharField(max_length=128, null=True, blank=True)  #

    API_Key = models.CharField(max_length=256, null=True, blank=True)  #
    API_Secret = models.CharField(max_length=256, null=True, blank=True)
    SubWebHook = models.CharField(max_length=256, null=True, blank=True)

    PhoneNumber = PhoneNumberField(null=True, blank=True)

    account_manager = models.BooleanField(default=False)

    class Meta:
        verbose_name = 'Profile'
        verbose_name_plural = 'Profiles'


    def __str__(self):
        return f'{self.User} {self.PhoneNumber}'

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import User


class RegisterForm(UserCreationForm):  # Extending UserCreationForm for registration
    username = forms.CharField(max_length=123, required=True)
    email = forms.EmailField(label="Email")

    class Meta:
        model = User
        fields = ("username", "email", "is_active")

accounts/views.py
from django.shortcuts import render, redirect

from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm, PasswordResetForm, AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.auth.models import User

from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse

from django.template.loader import render_to_string
from django.db.models.query_utils import Q
from django.utils.http import urlsafe_base64_encode
from django.contrib.auth.tokens import default_token_generator
from django.utils.encoding import force_bytes

from verify_email.email_handler import send_verification_email

from .models import Profile
from .forms import RegisterForm


# Create your views here.

def signup(request):
    if request.user.is_authenticated:
        return redirect('core:home')
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        phonenumber = request.POST.get('phonenumber')
        if form.is_valid():
            inactive_user = send_verification_email(request, form)  # Send verification email to in-active user
            Profile.objects.create(User=inactive_user, PhoneNumber=phonenumber)
            return redirect('accounts:email-activation')
        else:
            return render(request, 'accounts/signup.html', {'form': form})
    else:
        form = RegisterForm()
        return render(request, 'accounts/signup.html', {'form': form})


def signin(request):
    error = ''
    if request.user.is_authenticated:
        return redirect('core:home')
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)  # authenticate user's, email and password
        if user is not None:
            login(request, user)
            return redirect('core:home')
        else:
            error = 'Invalid Username or Password'
            form = AuthenticationForm(request.POST)
            return render(request, 'accounts/login.html', {'form': form, 'error': error})
    else:
        form = AuthenticationForm()
        return render(request, 'accounts/login.html', {'form': form})


def signout(request):
    logout(request)
    return redirect('accounts:login')


def password_reset_request(request):  # password reset for loged-out user
    if request.method == "POST":
        password_reset_form = PasswordResetForm(request.POST)
        if password_reset_form.is_valid():
            data = password_reset_form.cleaned_data['email']  # get user entered email
            associated_users = User.objects.filter(Q(email=data))  # find associated user with that email
            if associated_users.exists():
                for user in associated_users:
                    subject = "Password Reset Requested"
                    email_template_name = "accounts/password/password_reset_email.txt"  # email body stored in txt file
                    c = {
                        "email": user.email,
                        'domain': '127.0.0.1:8000',
                        'site_name': 'Website',
                        "uid": urlsafe_base64_encode(force_bytes(user.pk)),
                        "user": user,
                        'token': default_token_generator.make_token(user),
                        'protocol': 'http',
                    }
                    email = render_to_string(email_template_name, c)  # All email data rendered as string
                    try:
                        send_mail(subject, email, 'panda.throwawayyy@gmail.com', [user.email],
                                  fail_silently=True)  # Send Email
                    except BadHeaderError:
                        return HttpResponse('Invalid header found.')
                    return redirect("/password_reset/done/")
    password_reset_form = PasswordResetForm()
    return render(request=request, template_name="accounts/password/password_reset.html",
                  context={"password_reset_form": password_reset_form})


@login_required
def change_password(request):  # change password for logged-in user
    message = ''
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # converting password to hash
            message = 'Password changed successfully'
            return redirect('core:home')
    else:
        form = PasswordChangeForm(request.user)

    return render(request, 'accounts/password/password_reset_confirm.html', {'form': form, 'message': message})


def email_message(request):  # Show a message after signup process, to check email for verification
    return render(request, 'accounts/email_message.html')

templates/accounts/email_message.html
{% extends 'auth_base.html' %}
{% load static %}
{% block content %}
    <section class="flexbox-container">
        <div class="col-12 d-flex align-items-center justify-content-center">
            <div class="col-lg-4 col-md-6 col-10 box-shadow-2 p-0">
                <div class="card border-grey border-lighten-3 px-1 py-1 m-0">
                    <div class="card-header border-0">
                        <div class="text-center mb-1">
                            <img src="app-assets/images/logo/logo.png" alt="branding logo">
                        </div>
                        <div class="font-large-1  text-center">
                            Email Verification!
                        </div>
                    </div>
                    <div class="card-content">

                        <div class="card-body">
                            <h4 class="text-center">
                                <p>We have sent you a verification email,
                                    <br>
                                    please click on the link provided in the email to verify your account,
                                    <br>
                                    Check spam folder too.
                                </p>
                            </h4>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock %}

templates/accounts/error_file.html
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ field.label }} - {{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ field.label }} - {{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}

templates/accounts/login.html
{% extends 'auth_base.html' %}
{% load static %}

{% block content %}
    <section class="flexbox-container">
        <div class="col-12 d-flex align-items-center justify-content-center">
            <div class="col-lg-4 col-md-6 col-10 box-shadow-2 p-0">
                <div class="card border-grey border-lighten-3 px-1 py-1 m-0">
                    <div class="card-header border-0">
                        <div class="text-center mb-1">
                            <img src="app-assets/images/logo/logo.png" alt="branding logo">
                        </div>
                        <div class="font-large-1  text-center">
                            Member Login
                        </div>
                    </div>
                    <div class="card-content">

                        <div class="card-body">
                            <form class="form-horizontal" method="post">
                                {% csrf_token %}
                                {% if error %}
                                    <div class="alert alert-danger">
                                        <strong>{{ error }}</strong>
                                    </div>
                                {% endif %}
                                <fieldset class="form-group position-relative has-icon-left">
                                    <input type="text" class="form-control round" id="user-name"
                                           name="username" placeholder="Your Username" required>
                                    <div class="form-control-position">
                                        <i class="ft-user"></i>
                                    </div>
                                </fieldset>
                                <fieldset class="form-group position-relative has-icon-left">
                                    <input type="password" class="form-control round" id="user-password"
                                           name="password" placeholder="Enter Password" required>
                                    <div class="form-control-position">
                                        <i class="ft-lock"></i>
                                    </div>
                                </fieldset>
                                <div class="form-group row">
                                    <div class="col-md-6 col-12 text-center text-sm-left">

                                    </div>
                                    <div class="col-md-6 col-12 float-sm-left text-center text-sm-right"><a
                                            href="{% url 'accounts:password_reset' %}" class="card-link">Forgot Password?</a></div>
                                </div>
                                <div class="form-group text-center">
                                    <button type="submit"
                                            class="btn round btn-block btn-glow btn-bg-gradient-x-purple-blue col-12 mr-1 mb-1">
                                        Login
                                    </button>
                                </div>

                            </form>
                        </div>
                        <p class="card-subtitle text-muted text-right font-small-3 mx-2 my-1"><span>Don't have an account ? <a
                                href="{% url 'accounts:signup' %}" class="card-link">Sign Up</a></span></p>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

templates/accounts/signup.html
{% extends 'auth_base.html' %}
{% load  static %}
{% block content %}
    <section class="flexbox-container">
        <div class="col-12 d-flex align-items-center justify-content-center">
            <div class="col-lg-4 col-md-6 col-10 box-shadow-2 p-0">
                <div class="card border-grey border-lighten-3 px-1 py-1 m-0">
                    <div class="card-header border-0">
                        <div class="text-center mb-1">
                            <img src="app-assets/images/logo/logo.png" alt="branding logo">
                        </div>
                        <div class="font-large-1  text-center">
                            Become A Member
                        </div>
                    </div>
                    <div class="card-content">

                        <div class="card-body">
                            <form class="form-horizontal" method="post">
                                {% csrf_token %}
                                {% include 'accounts/error_file.html' %}
                                <fieldset class="form-group position-relative has-icon-left">
                                    <input type="text" class="form-control round" id="user-name"
                                           name="username" placeholder="Choose Username" required>
                                    <div class="form-control-position">
                                        <i class="ft-user"></i>
                                    </div>
                                </fieldset>
                                <fieldset class="form-group position-relative has-icon-left">
                                    <input type="email" class="form-control round" id="user-email"
                                           name="email" placeholder="Your Email Address" required>
                                    <div class="form-control-position">
                                        <i class="ft-mail"></i>
                                    </div>
                                </fieldset>
                                <fieldset class="form-group position-relative has-icon-left">
                                    <input type="tel" class="form-control round" id="phonenumber"
                                           name="phonenumber" placeholder="+91 111 1234567" required>
                                    <div class="form-control-position">
                                        <i class="ft-phone"></i>
                                    </div>
                                </fieldset>
                                <fieldset class="form-group position-relative has-icon-left">
                                    <input type="password" class="form-control round" id="user-password"
                                           name="password1" placeholder="Enter Password" required>
                                    <div class="form-control-position">
                                        <i class="ft-lock"></i>
                                    </div>
                                </fieldset>
                                <fieldset class="form-group position-relative has-icon-left">
                                    <input type="password" class="form-control round" id="user-password"
                                           name="password2" placeholder="Confirm Password" required>
                                    <div class="form-control-position">
                                        <i class="ft-lock"></i>
                                    </div>
                                </fieldset>

                                <div class="form-group text-center">
                                    <button type="submit"
                                            class="btn round btn-block btn-glow btn-bg-gradient-x-purple-blue col-12 mr-1 mb-1">
                                        Register
                                    </button>
                                </div>

                            </form>
                        </div>
                        <p class="card-subtitle text-muted text-right font-small-3 mx-2 my-1">
                            <span>Already a member ?
                                <a href="{% url 'accounts:login' %}" class="card-link">Sign In</a>
                            </span>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock %}