Neel_Stock/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('verification/', include('verify_email.urls')),
    path('', include('accounts.urls')),
    path('core/', include('core.urls')),
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='accounts/password/password_reset_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name="accounts/password/password_reset_confirm.html"),
         name='password_reset_confirm'),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password/password_reset_complete.html'),
         name='password_reset_complete'),

]

core/urls.py
from django.urls import path
from .views import user_lists, watch_lists, delete_userlist, delete_watchlist, update_userlist,get_ajax, home, user_buckets, update_bucket, delete_bucket

app_name = 'core'

urlpatterns = [
    # dashboard
    path('', home, name='home'),
    # create and list views
    path('user_lists/', user_lists, name='user_lists'),
    path('user_buckets/', user_buckets, name='user_buckets'),
    path('watch_list/', watch_lists, name='watch_list'),
    # edit views
    path('update_user/<int:pk>/', update_userlist.as_view(), name='update_user'),
    path('update_bucket/<int:pk>/', update_bucket.as_view(), name='update_bucket'),

    # delete views
    path('delete_userlist/<int:pk>/', delete_userlist, name='delete_userlist'),
    path('delete_bucket/<int:pk>/', delete_bucket, name='delete_bucket'),
    path('delete_watchlist/<int:pk>/', delete_watchlist, name='delete_watchlist'),

    # ltp view
    path('ltp/', get_ajax, name='get_ltp'),
]

accounts/models.py
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField
from django.contrib.auth.models import User

from core.choices import BROKER_CHOICES


# Create your models here.

class Profile(models.Model):
    User = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')

    Broker = models.CharField(max_length=15, choices=BROKER_CHOICES, null=True, blank=True)  #
    UserId = models.CharField(max_length=128, null=True, blank=True)  #

    Password = models.CharField(max_length=256, null=True, blank=True)  #

    Pin_2FA = models.CharField(max_length=128, null=True, blank=True)  #

    API_Key = models.CharField(max_length=256, null=True, blank=True)  #
    API_Secret = models.CharField(max_length=256, null=True, blank=True)
    SubWebHook = models.CharField(max_length=256, null=True, blank=True)

    PhoneNumber = PhoneNumberField(null=True, blank=True)

    account_manager = models.BooleanField(default=False)

    class Meta:
        verbose_name = 'Profile'
        verbose_name_plural = 'Profiles'


    def __str__(self):
        return f'{self.User} {self.PhoneNumber}'

core/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from .choices import VALIDITY_CHOICES, TRANS_CHOICES, BROKER_CHOICES, PRODUCT_TYPE_CHOICES, ADV_PRODUCT_TYPE, ORDER_TYPE_CHOICES
from phonenumber_field.modelfields import PhoneNumberField


# Create your models here.


class Bucket(models.Model):
    Creator = models.ForeignKey(User, on_delete=models.CASCADE, related_name='Bucket_Creator')
    Users = models.ManyToManyField(User, through='Multiplier')

    ActivateCopyTrade = models.BooleanField(default=False)

    created_at = models.DateTimeField(auto_now_add=True, editable=False, blank=True)
    updated_at = models.DateTimeField(auto_now=True, editable=False, blank=True)

    def __str__(self):
        users_query = self.Users.all()
        users_str = ''
        for user in users_query:
            users_str = users_str + user.username + ', '
        return f'{self.Creator} / {users_str} '

    def delete_object(self):
        return reverse('core:delete_bucket', args=[str(self.id)])

    class Meta:
        verbose_name = 'Bucket'
        verbose_name_plural = 'Buckets'


class Multiplier(models.Model):
    Bucket = models.ForeignKey(Bucket, on_delete=models.CASCADE)
    User = models.ForeignKey(User, on_delete=models.CASCADE)

    multiplier = models.PositiveIntegerField(default=1)


class Transaction(models.Model):
    User = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    Stock = models.CharField(max_length=200)
    Bucket = models.ForeignKey(Bucket, on_delete=models.PROTECT, null=True)

    Date = models.DateTimeField()

    Type = models.CharField(max_length=4, choices=TRANS_CHOICES)

    ProductType = models.CharField(max_length=7, choices=PRODUCT_TYPE_CHOICES, default='Regular')

    AdvanceProductType = models.CharField(max_length=8, choices=ADV_PRODUCT_TYPE, default='Intraday')

    OrderType = models.CharField(max_length=10, choices=ORDER_TYPE_CHOICES, default='Market')

    Validity = models.CharField(max_length=3, choices=VALIDITY_CHOICES, default='Day')

    Price = models.BooleanField(default=True)

    LimitPrice = models.FloatField(null=True, blank=True)
    StopPrice = models.FloatField(null=True, blank=True)
    StopLoss = models.FloatField(null=True, blank=True)
    TakeProfit = models.FloatField(null=True, blank=True)
    TrailingStopLoss = models.FloatField(null=True, blank=True)

    Quantity = models.PositiveIntegerField(null=True, blank=True)
    DisclosedQuantity = models.PositiveIntegerField(null=True, blank=True)

    created_at = models.DateTimeField(auto_now_add=True, editable=False, blank=True)
    updated_at = models.DateTimeField(auto_now=True, editable=False, blank=True)

    def __str__(self):
        return f'{self.User} {self.Stock} {self.Type} {self.Date}'

    class Meta:
        verbose_name = 'Transaction'
        verbose_name_plural = 'Transactions'


class WatchList(models.Model):
    User = models.ForeignKey(User, on_delete=models.CASCADE)

    Stocktoken = models.CharField(max_length=200, null=True)
    Stocksymbol = models.CharField(max_length=200, null=True)
    Stockname = models.CharField(max_length=200, null=True)
    Stockexch_seg = models.CharField(max_length=200, null=True)

    created_at = models.DateTimeField(auto_now_add=True, editable=False, blank=True)
    updated_at = models.DateTimeField(auto_now=True, editable=False, blank=True)

    def __str__(self):
        return f'{self.User} {self.Stocktoken}'

    def delete_object(self):
        return reverse('core:delete_watchlist', args=[str(self.id)])

    class Meta:
        verbose_name = 'WatchList'
        verbose_name_plural = 'WatchLists'


class Stock(models.Model):
    token = models.CharField(max_length=20)
    symbol = models.CharField(max_length=30)
    name = models.CharField(max_length=30)

    expiry = models.CharField(max_length=30)
    strike = models.CharField(max_length=30)
    lotsize = models.CharField(max_length=30)

    instrumenttype = models.CharField(max_length=30)
    exch_seg = models.CharField(max_length=30)

    tick_size = models.CharField(max_length=30)

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Stock'
        verbose_name_plural = 'Stock'

core/forms.py
from django import forms
from .models import WatchList, Stock, Transaction, Bucket


class BucketForm(forms.ModelForm):
    class Meta:
        model = Bucket
        exclude = ('Creator', 'created_at', 'updated_at')
        widgets = {
            'Users': forms.SelectMultiple(attrs={'class': 'form-control'}),
            'ActivateCopyTrade': forms.CheckboxInput(attrs={'class': 'form-control'}),
            'Multiplier': forms.NumberInput(attrs={'class': 'form-control'}),
        }


class TransactionForm(forms.ModelForm):
    class Meta:
        model = Transaction
        exclude = ('User', 'created_at', 'updated_at', 'Date')
        widgets = {
            'Stock': forms.TextInput(attrs={'class': 'form-control'}),
            'Type': forms.Select(attrs={'class': 'form-control'}),
            'Price': forms.CheckboxInput(attrs={'class': 'form-control'}),
            'LimitPrice': forms.NumberInput(attrs={'class': 'form-control'}),
            'StopPrice': forms.NumberInput(attrs={'class': 'form-control'}),
            'StopLoss': forms.NumberInput(attrs={'class': 'form-control'}),
            'TakeProfit': forms.NumberInput(attrs={'class': 'form-control'}),
            'TrailingStopLoss': forms.NumberInput(attrs={'class': 'form-control'}),
            'Quantity': forms.NumberInput(attrs={'class': 'form-control'}),
            'DisclosedQuantity': forms.NumberInput(attrs={'class': 'form-control'}),
        }

core/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required, user_passes_test
from django.views.generic import UpdateView
from django.utils import timezone
from datetime import datetime
from django.http import JsonResponse
from django.core import serializers
import json
from .models import *
from .forms import *
from django.contrib.auth.mixins import LoginRequiredMixin
from accounts.helper import SuperUserCheck, AccountManagerCheck
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from .helper import get_ltp_data


# Create your views here.
def home(request):
    obj = Stock.objects.all()
    trans = Transaction.objects.filter(User=request.user)
    bucket = Bucket.objects.filter(Creator=request.user)

    watch = WatchList.objects.filter(User=request.user)
    token_list = []

    for w in watch:
        token_list.append(w.Stocktoken)

    watch_stock = Stock.objects.filter(token__in=token_list)
    print("hekjfbwekjf------",watch_stock)
    if request.method == 'POST':
        form = TransactionForm(request.POST)
        print(form)
        if form.is_valid():
            inst = form.save(commit=False)
            inst.User = request.user
            inst.Date = datetime.now(tz=timezone.utc)
            inst.save()
    else:
        form = TransactionForm

    context = {
        'stocks': obj,
        'form': form,
        'trans': trans,
        'watch': watch_stock,
        'bucket': bucket,
    }

    return render(request, 'core/home.html', context)


@login_required()
@user_passes_test(lambda u: u.is_superuser or u.profile.account_manager)
def user_lists(request):
    obj = User.objects.all()
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
    else:
        form = UserCreationForm

    context = {
        'obj': obj,
        'form': form,
    }

    return render(request, 'core/user_lists.html', context)


class update_userlist(UpdateView, SuperUserCheck, AccountManagerCheck, LoginRequiredMixin):
    form_class = UserChangeForm
    model = User
    template_name = 'core/update_user.html'
    success_url = reverse_lazy('core:user_lists')


@login_required()
@user_passes_test(lambda u: u.is_superuser or u.profile.account_manager)
def delete_userlist(request, pk):
    User.objects.get(id=pk).delete()
    return redirect('core:user_lists')


@login_required()
@user_passes_test(lambda u: u.is_superuser or u.profile.account_manager)
def user_buckets(request):
    obj = Bucket.objects.filter(Creator=request.user)
    if request.method == 'POST':
        form = BucketForm(request.POST)
        if form.is_valid():
            buc = form.save(commit=False)
            buc.Creator = request.user
            buc.save()
            form.save_m2m()
    else:
        form = BucketForm

    context = {
        'obj': obj,
        'form': form,
    }

    return render(request, 'core/user_buckets.html', context)


class update_bucket(UpdateView, SuperUserCheck, AccountManagerCheck, LoginRequiredMixin):
    form_class = BucketForm
    model = Bucket
    template_name = 'core/update_bucket.html'
    success_url = reverse_lazy('core:user_buckets')


@login_required()
@user_passes_test(lambda u: u.is_superuser or u.profile.account_manager)
def delete_bucket(request, pk):
    Bucket.objects.get(id=pk).delete()
    return redirect('core:user_buckets')


@login_required(login_url='accounts:login')
def watch_lists(request):
    if request.method == 'POST':
        var = request.POST.get('stock')
        stonk = Stock.objects.get(token=var)
        WatchList.objects.create(
            User=request.user,
            Stocktoken=stonk.token, Stocksymbol=stonk.symbol,
            Stockname=stonk.name, Stockexch_seg=stonk.exch_seg
        )

    obj = Stock.objects.all()
    watch = WatchList.objects.filter(User=request.user)
    token_list = []

    for w in watch:
        token_list.append(w.Stocktoken)

    watch_stock = Stock.objects.filter(token__in=token_list)

    return render(request, 'core/watch_list.html', {'obj': obj, 'watch': watch_stock})


@login_required(login_url='accounts:login')
def delete_watchlist(request, pk):
    WatchList.objects.get(id=pk).delete()
    return redirect('core:watch_list')


def get_ajax(request):
    watch = WatchList.objects.filter(User=request.user)
    token_list = []

    for w in watch:
        token_list.append(w.Stocktoken)

    watch_stock = Stock.objects.filter(token__in=token_list)

    if request.is_ajax and request.method == 'GET':
        ltp = []
        print('got the request', watch_stock)
        for w in watch_stock:
            ltp.append(get_ltp_data(w))

        # instance = serializers.serialize('json', [watch_stock, ])
        print(ltp)
        # instance = json.dumps(ltp)

        return JsonResponse({'ltp': ltp}, status=200)

templates/core/update_bucket.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <div class="app-content content">
        <div class="content-wrapper">

            <section id="configuration">
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-header">
                                <h4 class="card-title">Edit</h4>
                            </div>
                            <div class="card-content collapse show">
                                <div class="card-body">
                                    <form method="post" class="form">
                                        {% csrf_token %}
                                        <div class="form-body">
                                            <h4 class="form-section">
                                                <i class="ft-list"></i> Edit Bucket</h4>
                                            {{ form }}
                                        </div>
                                        <div class="form-actions">
                                            <input type="submit" value="Save" class="btn btn-primary">
                                        </div>
                                    </form>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>

{% endblock %}

templates/core/user_lists.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <div class="app-content content">
        <div class="content-wrapper">

            <section id="configuration">
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-header">
                                <h4 class="card-title">Users</h4>
                                <a class="heading-elements-toggle"><i class="la la-ellipsis-v font-medium-3"></i></a>
                                <button type="button" data-toggle="modal" data-target="#adduser"
                                        class="float-right btn btn-round btn-glow btn-bg-gradient-x-purple-blue"
                                        style="color: white">Add User <i
                                        class="ft-plus-square" style="color: white"></i></button>
                            </div>
                            <div class="modal fade text-left" id="adduser" tabindex="-1" role="dialog"
                                 aria-labelledby="myModalLabel33" aria-hidden="true">
                                <div class="modal-dialog" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <label class="modal-title text-text-bold-600" id="myModalLabel33">
                                                Add User</label>
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                        <div class="card-content collapse show">
                                            <div class="card-body">
                                                <form method="post" class="form">
                                                    {% csrf_token %}
                                                    {% include 'form_errors.html' %}
                                                    <div class="form-body">
                                                        <h4 class="form-section">
                                                            <i class="ft-user"></i> Create User</h4>
                                                        <div class="form-group">
                                                            <label for="name">Name</label>
                                                            {{form.Name}}
                                                        </div>
                                                        <div class="row">
                                                            <div class="col-md-6">
                                                                <div class="form-group">
                                                                    <label for="email">Email</label>
                                                                    {{form.Email}}
                                                                </div>
                                                            </div>
                                                            <div class="col-md-6">
                                                                <div class="form-group">
                                                                    <label for="phone">Phone</label>
                                                                    {{form.Phone}}
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class="row">
                                                            <div class="col-md-6">
                                                                <div class="form-group">
                                                                    <label for="password">Password</label>
                                                                    {{form.Password}}
                                                                </div>
                                                            </div>
                                                            <div class="col-md-6">
                                                                <div class="form-group">
                                                                    <label for="userid">User ID</label>
                                                                    {{form.UserId}}
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class="row">
                                                            <div class="col-md-6">
                                                                <div class="form-group">
                                                                    <label for="id_Broker">Broker</label>
                                                                    {{form.Broker}}
                                                                </div>
                                                            </div>
                                                            <div class="col-md-6">
                                                                <div class="form-group">
                                                                    <label for="id_Pin_2FA">PIN/2FA</label>
                                                                    {{form.Pin_2FA}}
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class="row">
                                                            <div class="col-md-6">
                                                                <div class="form-group">
                                                                    <label for="id_API_Key">API Key</label>
                                                                    {{form.API_Key}}
                                                                </div>
                                                            </div>
                                                            <div class="col-md-6">
                                                                <div class="form-group">
                                                                    <label for="id_API_Secret">API Secret</label>
                                                                    {{form.API_Secret}}
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class="form-group">
                                                            <label for="id_SubWebHook">Sub Web Hook</label>
                                                            {{form.SubWebHook}}
                                                        </div>
                                                    </div>

                                                    <div class="form-actions">
                                                        <input type="submit" value="Save" class="btn btn-primary">
                                                    </div>
                                                </form>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="card-content collapse show">
                                <div class="card-body card-dashboard">
                                    <p class="card-text">List of Users added by you.</p>
                                    <div class="table-responsive">
                                        <table class="table table-striped table-bordered zero-configuration">
                                            <thead>
                                            <tr>
                                                <th>Name</th>
                                                <th>Broker</th>
                                                <th>User id</th>
                                                <th>Edit</th>
                                                <th>Delete</th>
                                            </tr>
                                            </thead>
                                            <tbody>
                                            {% for o in obj %}
                                                <tr>
                                                    <td>{{ o.Name }}</td>
                                                    <td>{{ o.Broker }}</td>
                                                    <td>{{ o.UserId }}</td>
                                                    <td><a href="{% url 'core:update_user' o.pk %}"><i class="ft-edit-3"></i></a></td>
                                                    <td><a data-toggle="modal" data-target="#delete{{ o.pk }}"> <i
                                                            class="ft-delete"></i></a></td>
                                                </tr>
                                                <div class="modal fade text-left" id="delete{{ o.pk }}" tabindex="-1"
                                                     role="dialog" aria-labelledby="basicModalLabel1"
                                                     aria-hidden="true">
                                                    <div class="modal-dialog" role="document">
                                                        <div class="modal-content">
                                                            <div class="modal-header">
                                                                <h4 class="modal-title" id="basicModalLabel1">Delete
                                                                    User</h4>
                                                                <button type="button" class="close" data-dismiss="modal"
                                                                        aria-label="Close">
                                                                    <span aria-hidden="true">&times;</span>
                                                                </button>
                                                            </div>
                                                            <div class="modal-body">
                                                                <p>Are you sure you want to delete User '{{ o.Name }}'?
                                                                    This action is irreversible!
                                                                </p>
                                                            </div>
                                                            <div class="modal-footer">
                                                                <button type="button" class="btn grey btn-secondary"
                                                                        data-dismiss="modal">Close
                                                                </button>
                                                                <a href="{% url 'core:delete_userlist' o.pk %}"
                                                                   class="btn btn-danger">Delete
                                                                </a>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>

                                            {% endfor %}
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>

        </div>
    </div>

{% endblock %}