Neel_Stock/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('verification/', include('verify_email.urls')),
    path('', include('accounts.urls')),
    path('core/', include('core.urls')),
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='accounts/password/password_reset_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name="accounts/password/password_reset_confirm.html"),
         name='password_reset_confirm'),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password/password_reset_complete.html'),
         name='password_reset_complete'),

]

accounts/urls.py
from django.urls import path
from .views import signin, signup, signout, change_password, password_reset_request, email_message

app_name = "accounts"   # App name for calling Url's in template/Html

urlpatterns = [
    path('', signin, name="login"),
    path('signout', signout, name="signout"),
    path('signup', signup, name="signup"),
    path('change-password', change_password, name="change-password"),
    path('password_reset/', password_reset_request, name="password_reset"),
    path('email-activation/', email_message, name="email-activation"),
]

core/urls.py
from django.urls import path
from .views import user_lists, watch_lists, delete_userlist, delete_watchlist, update_userlist,get_ajax, home, user_buckets, update_bucket, delete_bucket

app_name = 'core'

urlpatterns = [
    # dashboard
    path('', home, name='home'),
    # create and list views
    path('user_lists/', user_lists, name='user_lists'),
    path('user_buckets/', user_buckets, name='user_buckets'),
    path('watch_list/', watch_lists, name='watch_list'),
    # edit views
    path('update_user/<int:pk>/', update_userlist.as_view(), name='update_user'),
    path('update_bucket/<int:pk>/', update_bucket.as_view(), name='update_bucket'),

    # delete views
    path('delete_userlist/<int:pk>/', delete_userlist, name='delete_userlist'),
    path('delete_bucket/<int:pk>/', delete_bucket, name='delete_bucket'),
    path('delete_watchlist/<int:pk>/', delete_watchlist, name='delete_watchlist'),

    # ltp view
    path('ltp/', get_ajax, name='get_ltp'),
]

templates/auth_base.html
{% load static %}
<!DOCTYPE html>
<html class="loading" lang="en" data-textdirection="ltr">
<!-- BEGIN: Head-->

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
    <meta name="description" content="Chameleon Admin is a modern Bootstrap 4 webapp &amp; admin dashboard html template with a large number of components, elegant design, clean and organized code.">
    <meta name="keywords" content="admin template, Chameleon admin template, dashboard template, gradient admin template, responsive admin template, webapp, eCommerce dashboard, analytic dashboard">
    <meta name="author" content="ThemeSelect">
    <title>Login - Chameleon Admin - Modern Bootstrap 4 WebApp & Dashboard HTML Template + UI Kit</title>
    <link rel="apple-touch-icon" href="app-assets/images/ico/apple-icon-120.png">
    <link rel="shortcut icon" type="image/x-icon" href="app-assets/images/ico/favicon.ico">
    <link href="https://fonts.googleapis.com/css?family=Muli:300,300i,400,400i,600,600i,700,700i%7CComfortaa:300,400,700" rel="stylesheet">

    <!-- BEGIN: Vendor CSS-->
    <link rel="stylesheet" type="text/css" href="{% static 'app-assets/vendors/css/vendors.min.css' %}">
    <!-- END: Vendor CSS-->

    <!-- BEGIN: Theme CSS-->
    <link rel="stylesheet" type="text/css" href="{% static 'app-assets/css/bootstrap.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'app-assets/css/bootstrap-extended.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'app-assets/css/colors.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'app-assets/css/components.css' %}">
    <!-- END: Theme CSS-->

    <!-- BEGIN: Page CSS-->
    <link rel="stylesheet" type="text/css" href="{% static 'app-assets/css/core/menu/menu-types/vertical-menu.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'app-assets/css/core/colors/palette-gradient.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'app-assets/css/pages/login-register.css' %}">
    <!-- END: Page CSS-->

    <!-- BEGIN: Custom CSS-->
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/style.css' %}">
    <!-- END: Custom CSS-->

</head>
<!-- END: Head-->

<!-- BEGIN: Body-->

<body class="vertical-layout vertical-menu 1-column  bg-full-screen-image blank-page blank-page" data-open="click" data-menu="vertical-menu" data-color="bg-gradient-x-purple-blue" data-col="1-column">
    <!-- BEGIN: Content-->
    <div class="app-content content">
        <div class="content-wrapper">
            <div class="content-wrapper-before"></div>
            <div class="content-header row">
            </div>
            <div class="content-body">
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </div>
    <!-- END: Content-->


    <!-- BEGIN: Vendor JS-->
    <script src="{% static 'app-assets/vendors/js/vendors.min.js' %}" type="text/javascript"></script>
    <!-- BEGIN Vendor JS-->

    <!-- BEGIN: Page Vendor JS-->
    <script src="{% static 'app-assets/vendors/js/forms/validation/jqBootstrapValidation.js' %}" type="text/javascript"></script>
    <!-- END: Page Vendor JS-->

    <!-- BEGIN: Theme JS-->
    <script src="{% static 'app-assets/js/core/app-menu.js' %}" type="text/javascript"></script>
    <script src="{% static 'app-assets/js/core/app.js' %}" type="text/javascript"></script>
    <!-- END: Theme JS-->

    <!-- BEGIN: Page JS-->
    <script src="{% static 'app-assets/js/scripts/forms/form-login-register.js' %}" type="text/javascript"></script>
    <!-- END: Page JS-->

</body>
<!-- END: Body-->

</html>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html class="loading" lang="en" data-textdirection="ltr">
<!-- BEGIN: Head-->

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
    <meta name="description" content="Chameleon Admin is a modern Bootstrap 4 webapp &amp; admin dashboard html template with a large number of components, elegant design, clean and organized code.">
    <meta name="keywords" content="admin template, Chameleon admin template, dashboard template, gradient admin template, responsive admin template, webapp, eCommerce dashboard, analytic dashboard">
    <meta name="author" content="ThemeSelect">
    <title>Neel Stock</title>
    <link rel="apple-touch-icon" href="{% static 'app-assets/images/ico/apple-icon-120.png' %}">
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'app-assets/images/ico/favicon.ico' %}">
    <link href="https://fonts.googleapis.com/css?family=Muli:300,300i,400,400i,600,600i,700,700i%7CComfortaa:300,400,700" rel="stylesheet">

    <!-- BEGIN: Vendor CSS-->
    <link rel="stylesheet" type="text/css" href="{% static 'app-assets/vendors/css/vendors.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'app-assets/vendors/css/tables/datatable/datatables.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'app-assets/vendors/css/forms/icheck/icheck.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'app-assets/vendors/css/forms/icheck/custom.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'app-assets/vendors/css/forms/selects/select2.min.css' %}">

    <link rel="stylesheet" type="text/css" href="{% static 'app-assets/vendors/css/charts/chartist.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'app-assets/vendors/css/charts/chartist-plugin-tooltip.css' %}">
    <!-- END: Vendor CSS-->

    <!-- BEGIN: Theme CSS-->
    <link rel="stylesheet" type="text/css" href="{% static 'app-assets/css/bootstrap.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'app-assets/css/bootstrap-extended.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'app-assets/css/colors.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'app-assets/css/components.css' %}">
    <!-- END: Theme CSS-->

    <!-- BEGIN: Page CSS-->
    <link rel="stylesheet" type="text/css" href="{% static 'app-assets/css/core/menu/menu-types/vertical-menu.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'app-assets/css/core/colors/palette-gradient.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'app-assets/css/core/colors/palette-gradient.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'app-assets/css/pages/chat-application.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'app-assets/css/pages/dashboard-analytics.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'app-assets/css/plugins/forms/checkboxes-radios.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'app-assets/css/plugins/forms/checkboxes-radios.css' %}">
    <!-- END: Page CSS-->

    <!-- BEGIN: Custom CSS-->
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/style.css' %}">
    <!-- END: Custom CSS-->

</head>
<!-- END: Head-->

<!-- BEGIN: Body-->

<body class="vertical-layout vertical-menu 2-columns   fixed-navbar" data-open="click" data-menu="vertical-menu" data-color="bg-gradient-x-purple-blue" data-col="2-columns">

    <!-- BEGIN: Header-->
    <nav class="header-navbar navbar-expand-md navbar navbar-with-menu navbar-without-dd-arrow fixed-top navbar-semi-light">
        <div class="navbar-wrapper">
            <div class="navbar-container content">
                <div class="collapse navbar-collapse show" id="navbar-mobile">
                    <ul class="nav navbar-nav mr-auto float-left">
                    <!-- header content here for left side, if any -->
                        <li class="nav-item mobile-menu d-md-none mr-auto"><a class="nav-link nav-menu-main menu-toggle hidden-xs" href="#"><i class="ft-menu font-large-1"></i></a></li>
                        <li class="nav-item d-none d-md-block"><a class="nav-link nav-menu-main menu-toggle hidden-xs" href="#"><i class="ft-menu"></i></a></li>
                        <li class="nav-item"><a class="nav-link nav-menu-main" href="{% url 'core:home' %}">Dashboard</a></li>
                        <li class="nav-item"><a class="nav-link nav-menu-main" href="{% url 'core:user_lists' %}">User Lists</a></li>
                        <li class="nav-item"><a class="nav-link nav-menu-main" href="{% url 'core:user_buckets' %}">User Buckets</a></li>
                        <li class="nav-item"><a class="nav-link nav-menu-main" href="{% url 'core:watch_list' %}">Watch List</a></li>
                    </ul>
                    <ul class="nav navbar-nav float-right">

                        <li class="dropdown dropdown-user nav-item"><a class="dropdown-toggle nav-link dropdown-user-link" href="#" data-toggle="dropdown"> <span class="avatar avatar-online"><img src="{% static 'app-assets/images/portrait/small/avatar-s-19.png' %}" alt="avatar"></span></a>
                            <div class="dropdown-menu dropdown-menu-right">
                                <div class="arrow_box_right"><a class="dropdown-item" href="#"><span class="avatar avatar-online"><img src="{% static 'app-assets/images/portrait/small/avatar-s-19.png' %}" alt="avatar"><span class="user-name text-bold-700 ml-1">John Doe</span></span></a>
                                    <div class="dropdown-divider"></div><a class="dropdown-item" href="{% url 'accounts:change-password' %}"><i class="ft-user"></i> Change Password</a>
                                    <div class="dropdown-divider"></div><a class="dropdown-item" href="{% url 'accounts:signout' %}"><i class="ft-power"></i> Logout</a>
                                </div>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </nav>
    <!-- END: Header-->


    <!-- BEGIN: Main Menu-->
    {% block main_menu %}
    <div class="main-menu menu-fixed menu-light menu-accordion    menu-shadow " data-scroll-to-active="true" data-img="{% static 'app-assets/images/backgrounds/02.jpg' %}">
        <div class="navbar-header">
            <ul class="nav navbar-nav flex-row">
                <li class="nav-item mr-auto"><a class="navbar-brand" href="{% url 'core:home' %}"><img class="brand-logo" alt="Chameleon admin logo" src="{% static 'app-assets/images/logo/logo.png' %}" />
                        <h3 class="brand-text">Chameleon</h3>
                    </a></li>
                <li class="nav-item d-md-none"><a class="nav-link close-navbar"><i class="ft-x"></i></a></li>
            </ul>
        </div>
        <div class="navigation-background"></div>
        <div class="main-menu-content">
            <ul class="navigation navigation-main" id="main-menu-navigation" data-menu="menu-navigation">
                <!-- watch list goes here -->
            </ul>
        </div>
    </div>
    {% endblock %}
    <!-- END: Main Menu-->

    <!-- BEGIN: Content from app-content -->
    {% block content %}



    {% endblock %}
    <!-- END: Content-->


    <!-- BEGIN: Footer-->
    <footer class="footer footer-static footer-light navbar-border navbar-shadow">
        <div class="clearfix blue-grey lighten-2 text-sm-center mb-0 px-2"><span class="float-md-left d-block d-md-inline-block">2019 &copy; Copyright <a class="text-bold-800 grey darken-2" href="https://themeselection.com" target="_blank">ThemeSelection</a></span>
            <ul class="list-inline float-md-right d-block d-md-inline-blockd-none d-lg-block mb-0">
                <li class="list-inline-item"><a class="my-1" href="https://themeselection.com/" target="_blank"> More themes</a></li>
                <li class="list-inline-item"><a class="my-1" href="https://themeselection.com/support" target="_blank"> Support</a></li>
            </ul>
        </div>
    </footer>
    <!-- END: Footer-->


    <!-- BEGIN: Vendor JS-->
    <script src="{% static 'app-assets/vendors/js/vendors.min.js' %}" type="text/javascript"></script>
    <!-- BEGIN Vendor JS-->
  <!-- BEGIN: Page Vendor JS-->

    <script src="{% static 'app-assets/vendors/js/tables/datatable/datatables.min.js' %}" type="text/javascript"></script>
    <!-- END: Page Vendor JS-->
    {% block extrajs %}
    {% endblock %}

    <!-- BEGIN: Page Vendor JS-->
    <script src="{% static 'app-assets/vendors/js/charts/chartist.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'app-assets/vendors/js/charts/chartist-plugin-tooltip.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'app-assets/vendors/js/forms/icheck/icheck.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'app-assets/vendors/js/forms/select/select2.full.min.js' %}" type="text/javascript"></script>
    <!-- END: Page Vendor JS-->

    <!-- BEGIN: Theme JS-->
    <script src="{% static 'app-assets/js/core/app-menu.js' %}" type="text/javascript"></script>
    <script src="{% static 'app-assets/js/core/app.js' %}" type="text/javascript"></script>
    <!-- END: Theme JS-->

    <!-- BEGIN: Page JS-->
    <script src="{% static 'app-assets/js/scripts/pages/dashboard-analytics.js' %}" type="text/javascript"></script>
    <script src="{% static 'app-assets/js/scripts/forms/checkbox-radio.js' %}" type="text/javascript"></script>
    <script src="{% static 'app-assets/js/scripts/forms/select/form-select2.js' %}" type="text/javascript"></script>
    <!-- END: Page JS-->
     <!-- BEGIN: Page JS-->
    <script src="{% static 'app-assets/js/scripts/tables/datatables/datatable-basic.js' %}" type="text/javascript"></script>
    <!-- END: Page JS-->

</body>
<!-- END: Body-->

</html>

templates/form_errors.html
<ul class="errorlist">
  {% if form.non_field_errors %}
    <li>{{ form.non_field_errors }}</li>
  {% endif %}
  {% for field in form %}
    {% if field.errors %}
      <li>
        {{ field.label }}
        <ul class="errorlist">
          {% for error in field.errors %}
            <li>{{ error }}</li>
          {% endfor %}
        </ul>
      </li>
    {% endif %}
  {% endfor %}
</ul>